from server.services.planner_service import Route
from server.services.retriever_agent import retrieve
from server.services.summarization_service import summarize
from server.services.tool_service import count_uploaded_pdfs

from server.services.multi_tool.tool_selector import select_tools
from server.services.multi_tool.multi_tool_executor import execute_multiple_tools
from server.services.multi_tool.result_formatter import format_multi_tool_results
from server.services.mcp.mcp_orchestrator import execute_mcp_tools

from server.services.llm_service import generate_response
from server.services.integrations.github.github_tool import github_get_recent_activity
from server.services.integrations.gmail.gmail_tool import (
    gmail_get_profile,
    gmail_send_email,
)

from datetime import datetime, timedelta, timezone

from server.services.integrations.gmail.gmail_tool import (
    gmail_search_messages,
)

from server.services.integrations.calendar.calendar_tool import (
    calendar_create_event,
)

from server.services.llm_service import generate_response

def execute(
    plan: dict,
    question: str,
    history=None,
    user_id: int = None,
    conversation_id: int = None,
):
    """
    Execute the structured plan generated by the LLM planner.
    """

    route = plan["route"]

    # -----------------------------
    # Retrieval
    # -----------------------------
    if route == Route.RETRIEVAL:
        return retrieve(
            question,
            history=history,
            user_id=user_id,
            conversation_id=conversation_id,
        )

    # -----------------------------
    # Summarization
    # -----------------------------
    elif route == Route.SUMMARIZATION:

        summary = summarize(question)

        if summary is None:
            return {
                "answer": "No relevant information found.",
                "sources": [],
            }

        return {
            "answer": summary,
            "sources": [],
        }

    # -----------------------------
    # Tool
    # -----------------------------
    elif route == Route.TOOL:

        from server.services.tool_dispatcher import dispatch_tool

        tool = plan.get("tool")
        intent = plan.get("intent")
        parameters = plan.get("parameters", {})

        if not tool:
            raise ValueError("Tool route requires a tool.")

        if not intent:
            raise ValueError("Tool route requires an intent.")

        # =========================================================
        # GitHub -> Gmail chained workflow
        # =========================================================
        question_lower = question.lower()

        github_email_request = (
            "github" in question_lower
            and any(
                phrase in question_lower
                for phrase in [
                    "email me",
                    "email it",
                    "email a summary",
                    "send me an email",
                    "send an email",
                    "mail me",
                ]
            )
            and any(
                phrase in question_lower
                for phrase in [
                    "recent activity",
                    "latest activity",
                    "most recent activity",
                    "github activity",
                ]
            )
        )

        if github_email_request:
            # Step 1: Get GitHub activity
            github_result = github_get_recent_activity(
                user_id=user_id,
                max_results=20,
            )

            # Step 2: Create a concise email summary
            summary_prompt = f"""
Create a concise professional email summary from the following
GitHub activity.

Do not create an email subject.
Do not add a greeting or signature.
Only return the email body.

GitHub activity:
{github_result}
"""

            email_body = generate_response(summary_prompt).strip()

            # Step 3: Get the user's connected Gmail address
            gmail_profile = gmail_get_profile(user_id=user_id)

            recipient = gmail_profile.get("email")

            if not recipient:
                raise ValueError(
                    "Unable to determine your connected Gmail address."
                )

            # Step 4: Send the email
            send_result = gmail_send_email(
                user_id=user_id,
                to=recipient,
                subject="GitHub Activity Summary",
                body=email_body,
            )

            return {
                "answer": (
                    "## ✅ GitHub activity emailed successfully!\n\n"
                    f"**To:** {recipient}\n\n"
                    "**Subject:** GitHub Activity Summary"
                ),
                "sources": [],
            }

        # =========================================================
        # Calendar -> Gmail chained workflow
        # =========================================================
        calendar_email_request = (
            any(
                phrase in question_lower
                for phrase in [
                    "calendar",
                    "calendar events",
                    "upcoming events",
                    "meetings",
                    "schedule",
                ]
            )
            and any(
                phrase in question_lower
                for phrase in [
                    "email me",
                    "email a summary",
                    "send me an email",
                    "send an email",
                    "mail me",
                ]
            )
            and any(
                phrase in question_lower
                for phrase in [
                    "summary",
                    "summarize",
                    "summarise",
                ]
            )
        )

        if calendar_email_request:
            # Step 1: Get upcoming calendar events
            calendar_result = dispatch_tool(
                tool="calendar",
                action="tomorrow_events",
                params={"max_results": 10},
                user_id=user_id,
                question=question,
            )

            # Step 2: Create a concise email summary
            summary_prompt = f"""
Create a concise professional email summary from the following
calendar events.

Do not create an email subject.
Do not add a greeting or signature.
Only return the email body.

Calendar events:
{calendar_result}
"""

            email_body = generate_response(summary_prompt).strip()

            # Step 3: Get the user's connected Gmail address
            gmail_profile = gmail_get_profile(user_id=user_id)

            recipient = gmail_profile.get("email")

            if not recipient:
                raise ValueError(
                    "Unable to determine your connected Gmail address."
                )

            # Step 4: Send the email
            gmail_send_email(
                user_id=user_id,
                to=recipient,
                subject="Calendar Events Summary",
                body=email_body,
            )

            return {
                "answer": (
                    "## ✅ Calendar summary emailed successfully!\n\n"
                    f"**To:** {recipient}\n\n"
                    "**Subject:** Calendar Events Summary"
                ),
                "sources": [],
            }

        # =========================================================
        # Gmail -> Calendar chained workflow
        # =========================================================
        gmail_calendar_request = (
            any(
                phrase in question_lower
                for phrase in [
                    "email",
                    "emails",
                    "gmail",
                    "mail",
                ]
            )
            and any(
                phrase in question_lower
                for phrase in [
                    "calendar",
                    "schedule",
                    "add to my calendar",
                    "put on my calendar",
                ]
            )
            and any(
                phrase in question_lower
                for phrase in [
                    "summary",
                    "summarize",
                    "summarise",
                ]
            )
        )

        if gmail_calendar_request:
            # Step 1: Search recent WorkMind emails
            gmail_result = gmail_search_messages(
                user_id=user_id,
                query="WorkMind newer_than:7d",
                max_results=10,
            )

            if not gmail_result or gmail_result == "No matching emails found.":
                return {
                    "answer": "No recent WorkMind emails were found.",
                    "sources": [],
                }

            # Step 2: Create a concise calendar summary
            summary_prompt = f"""
Create a concise summary of the following WorkMind emails.

This summary will be added to a calendar event.
Include only important information, actions, deadlines,
decisions, or useful updates.

Do not include verification tokens, sensitive information,
or verification URLs.

Only return the summary text.

Emails:
{gmail_result}
"""

            email_summary = generate_response(summary_prompt).strip()

            # Step 3: Create tomorrow's calendar event at 11 AM
            india_timezone = timezone(timedelta(hours=5, minutes=30))

            tomorrow = (
                datetime.now(india_timezone).date()
                + timedelta(days=1)
            )

            start_datetime = datetime(
                tomorrow.year,
                tomorrow.month,
                tomorrow.day,
                11,
                0,
                0,
                tzinfo=india_timezone,
            )

            end_datetime = start_datetime + timedelta(hours=1)

            event = calendar_create_event(
                user_id=user_id,
                summary="WorkMind Email Summary",
                start_datetime=start_datetime.isoformat(),
                end_datetime=end_datetime.isoformat(),
                description=email_summary,
            )

            return {
                "answer": (
                    "## ✅ Gmail summary added to calendar!\n\n"
                    f"**Event:** {event.get('summary', 'WorkMind Email Summary')}\n"
                    f"**Start:** {start_datetime.isoformat()}\n"
                    f"**End:** {end_datetime.isoformat()}\n\n"
                    f"**Summary:**\n{email_summary}"
                ),
                "sources": [],
            }

        # =========================================================
        # Normal single-tool workflow
        # =========================================================

        result = dispatch_tool(
            tool=tool,
            action=intent,
            params=parameters,
            user_id=user_id,
            question=question,
        )

        return {
            "answer": result,
            "sources": [],
        }

    return None

